version: '3.3'

services:
  hugo:
    image: jguyomard/hugo-builder:0.32
    entrypoint: hugo --config ./config.toml
    volumes:
      - .:/src

  server:
    image: jguyomard/hugo-builder:0.32
    command: hugo server --bind 0.0.0.0
    ports:
      - "1313:1313"
    volumes:
      - .:/src